In [26]:
# Import dependencies
import pandas as pd
import numpy as np

In [27]:
# Read in population csv
popn_df =pd.read_csv('resources/population.csv', skiprows=4)
popn_df.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,Unnamed: 66
0,Aruba,ABW,"Population, total",SP.POP.TOTL,54608.0,55811.0,56682.0,57475.0,58178.0,58782.0,...,102880.0,103594.0,104257.0,104874.0,105439.0,105962.0,106442.0,106585.0,106537.0,NaN
1,Africa Eastern and Southern,AFE,"Population, total",SP.POP.TOTL,130692579.0,134169237.0,137835590.0,141630546.0,145605995.0,149742351.0,...,567891875.0,583650827.0,600008150.0,616377331.0,632746296.0,649756874.0,667242712.0,685112705.0,702976832.0,NaN
2,Afghanistan,AFG,"Population, total",SP.POP.TOTL,8622466.0,8790140.0,8969047.0,9157465.0,9355514.0,9565147.0,...,31541209.0,32716210.0,33753499.0,34636207.0,35643418.0,36686784.0,37769499.0,38972230.0,40099462.0,NaN
3,Africa Western and Central,AFW,"Population, total",SP.POP.TOTL,97256290.0,99314028.0,101445032.0,103667517.0,105959979.0,108336203.0,...,387204553.0,397855507.0,408690375.0,419778384.0,431138704.0,442646825.0,454306063.0,466189102.0,478185907.0,NaN
4,Angola,AGO,"Population, total",SP.POP.TOTL,5357195.0,5441333.0,5521400.0,5599827.0,5673199.0,5736582.0,...,26147002.0,27128337.0,28127721.0,29154746.0,30208628.0,31273533.0,32353588.0,33428486.0,34503774.0,NaN

In [3]:
# Read in gdp csv
gdp_df =pd.read_csv('resources/gdp.csv', skiprows=4)

In [4]:
# Read in electricity csv
elec_df =pd.read_csv('resources/MES_0123.csv', skiprows=8)

In [15]:
# Read in country lat and lon csv
country_df =pd.read_csv('resources/countries.csv')

In [17]:
continent_df = pd.read_csv('resources/continents2.csv')

In [ ]:
main_df = pd.merge(main_df,df2[['alpha-2','alpha-3','name']],on='Key_Column', how='left')

In [18]:
continent_df

,name,alpha-2,alpha-3,country-code,iso_3166-2,region,sub-region,intermediate-region,region-code,sub-region-code,intermediate-region-code
0,Afghanistan,AF,AFG,4,ISO 3166-2:AF,Asia,Southern Asia,NaN,142.0,34.0,NaN
1,Ã…land Islands,AX,ALA,248,ISO 3166-2:AX,Europe,Northern Europe,NaN,150.0,154.0,NaN
2,Albania,AL,ALB,8,ISO 3166-2:AL,Europe,Southern Europe,NaN,150.0,39.0,NaN
3,Algeria,DZ,DZA,12,ISO 3166-2:DZ,Africa,Northern Africa,NaN,2.0,15.0,NaN
4,American Samoa,AS,ASM,16,ISO 3166-2:AS,Oceania,Polynesia,NaN,9.0,61.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
244,Wallis and Futuna,WF,WLF,876,ISO 3166-2:WF,Oceania,Polynesia,NaN,9.0,61.0,NaN
245,Western Sahara,EH,ESH,732,ISO 3166-2:EH,Africa,Northern Africa,NaN,2.0,15.0,NaN
246,Yemen,YE,YEM,887,ISO 3166-2:YE,Asia,Western Asia,NaN,142.0,145.0,NaN
247,Zambia,ZM,ZMB,894,ISO 3166-2:ZM,Africa,Sub-Saharan Africa,Eastern Africa,2.0,202.0,14.0
248,Zimbabwe,ZW,ZWE,716,ISO 3166-2:ZW,Africa,Sub-Saharan Africa,Eastern Africa,2.0,202.0,14.0

In [16]:
country_df

    country   latitude  longitude                  name
0        AD  42.546245   1.601554               Andorra
1        AE  23.424076  53.847818  United Arab Emirates
2        AF  33.939110  67.709953           Afghanistan
3        AG  17.060816 -61.796428   Antigua and Barbuda
4        AI  18.220554 -63.068615              Anguilla
..      ...        ...        ...                   ...
240      YE  15.552727  48.516388                 Yemen
241      YT -12.827500  45.166244               Mayotte
242      ZA -30.559482  22.937506          South Africa
243      ZM -13.133897  27.849332                Zambia
244      ZW -19.015438  29.154857              Zimbabwe

[245 rows x 4 columns]

In [5]:
country_list = elec_df['Country'].unique()
print(len(country_list))

53

In [6]:
country_list_df = pd.DataFrame(country_list,columns=['Country Name'])
country_list_df.head()

  Country Name
0    Australia
1      Austria
2      Belgium
3       Canada
4        Chile

In [7]:
main_df = pd.merge(country_list_df,popn_df,how='inner',on='Country Name')
main_df

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,Unnamed: 66
0,Australia,AUS,"Population, total",SP.POP.TOTL,10276477.0,10483000.0,10742000.0,10950000.0,11167000.0,11388000.0,...,2.312813e+07,2.347569e+07,2.381600e+07,2.419091e+07,2.459420e+07,2.496664e+07,2.534022e+07,2.565529e+07,2.568808e+07,NaN
1,Austria,AUT,"Population, total",SP.POP.TOTL,7047539.0,7086299.0,7129864.0,7175811.0,7223801.0,7270889.0,...,8.479823e+06,8.546356e+06,8.642699e+06,8.736668e+06,8.797566e+06,8.840521e+06,8.879920e+06,8.916864e+06,8.955797e+06,NaN
2,Belgium,BEL,"Population, total",SP.POP.TOTL,9153489.0,9183948.0,9220578.0,9289770.0,9378113.0,9463667.0,...,1.115941e+07,1.120906e+07,1.127420e+07,1.133142e+07,1.137516e+07,1.142705e+07,1.148898e+07,1.153860e+07,1.159295e+07,NaN
3,Canada,CAN,"Population, total",SP.POP.TOTL,17909356.0,18271000.0,18614000.0,18964000.0,19325000.0,19678000.0,...,3.508295e+07,3.543744e+07,3.570291e+07,3.610949e+07,3.654524e+07,3.706508e+07,3.760123e+07,3.803720e+07,3.824611e+07,NaN
4,Chile,CHL,"Population, total",SP.POP.TOTL,8141820.0,8313535.0,8486120.0,8656006.0,8825046.0,8994936.0,...,1.750992e+07,1.768711e+07,1.787012e+07,1.808388e+07,1.836858e+07,1.870145e+07,1.903948e+07,1.930032e+07,1.949318e+07,NaN
5,Colombia,COL,"Population, total",SP.POP.TOTL,15687688.0,16182414.0,16691282.0,17210956.0,17739754.0,18275814.0,...,4.623793e+07,4.667795e+07,4.711973e+07,4.762596e+07,4.835167e+07,4.927696e+07,5.018741e+07,5.093066e+07,5.151656e+07,NaN
6,Costa Rica,CRI,"Population, total",SP.POP.TOTL,1346302.0,1396138.0,1447037.0,1498647.0,1550661.0,1602736.0,...,4.791535e+06,4.844288e+06,4.895242e+06,4.945205e+06,4.993842e+06,5.040734e+06,5.084532e+06,5.123105e+06,5.153957e+06,NaN
7,Denmark,DNK,"Population, total",SP.POP.TOTL,4579603.0,4611687.0,4647727.0,4684483.0,4722072.0,4759012.0,...,5.614932e+06,5.643475e+06,5.683483e+06,5.728010e+06,5.764980e+06,5.793636e+06,5.814422e+06,5.831404e+06,5.856733e+06,NaN
8,Estonia,EST,"Population, total",SP.POP.TOTL,1211537.0,1225077.0,1241623.0,1258857.0,1277086.0,1294566.0,...,1.317997e+06,1.314545e+06,1.315407e+06,1.315790e+06,1.317384e+06,1.321977e+06,1.326898e+06,1.329522e+06,1.330932e+06,NaN
9,Finland,FIN,"Population, total",SP.POP.TOTL,4429634.0,4461005.0,4491443.0,4523309.0,4548543.0,4563732.0,...,5.438972e+06,5.461512e+06,5.479531e+06,5.495303e+06,5.508214e+06,5.515525e+06,5.521606e+06,5.529543e+06,5.541017e+06,NaN
10,France,FRA,"Population, total",SP.POP.TOTL,46649927.0,47161641.0,47679792.0,48189939.0,48733997.0,49282756.0,...,6.600229e+07,6.631207e+07,6.654827e+07,6.672410e+07,6.691802e+07,6.715835e+07,6.738800e+07,6.757111e+07,6.774963e+07,NaN
11,Germany,DEU,"Population, total",SP.POP.TOTL,72814900.0,73377632.0,74025784.0,74714353.0,75318337.0,75963695.0,...,8.064560e+07,8.098250e+07,8.168661e+07,8.234867e+07,8.265700e+07,8.290578e+07,8.309296e+07,8.316087e+07,8.319608e+07,NaN
12,Greece,GRC,"Population, total",SP.POP.TOTL,8331725.0,8398050.0,8448233.0,8479625.0,8510429.0,8550333.0,...,1.096521e+07,1.089241e+07,1.082088e+07,1.077597e+07,1.075468e+07,1.073288e+07,1.072158e+07,1.069860e+07,1.064122e+07,NaN
13,Hungary,HUN,"Population, total",SP.POP.TOTL,9983967.0,10029321.0,10061734.0,10087947.0,10119835.0,10147935.0,...,9.893082e+06,9.866468e+06,9.843028e+06,9.814023e+06,9.787966e+06,9.775564e+06,9.771141e+06,9.750149e+06,9.709891e+06,NaN
14,Iceland,ISL,"Population, total",SP.POP.TOTL,175574.0,179029.0,182378.0,185653.0,188983.0,192286.0,...,3.237640e+05,3.273860e+05,3.308150e+05,3.354390e+05,3.434000e+05,3.527210e+05,3.605630e+05,3.664630e+05,3.725200e+05,NaN
15,Ireland,IRL,"Population, total",SP.POP.TOTL,2828600.0,2824400.0,2836050.0,2852650.0,2866550.0,2877300.0,...,4.623816e+06,4.657740e+06,4.701957e+06,4.755335e+06,4.807388e+06,4.867316e+06,4.934340e+06,4.985382e+06,5.033165e+06,NaN
16,Italy,ITA,"Population, total",SP.POP.TOTL,50199700.0,50536350.0,50879450.0,51252000.0,51675350.0,52112350.0,...,6.023395e+07,6.078914e+07,6.073058e+07,6.062750e+07,6.053671e+07,6.042176e+07,5.972908e+07,5.943885e+07,5.910967e+07,NaN
17,Japan,JPN,"Population, total",SP.POP.TOTL,93216000.0,94055000.0,94933000.0,95900000.0,96903000.0,97952000.0,...,1.274450e+08,1.272760e+08,1.271410e+08,1.270760e+08,1.269720e+08,1.268110e+08,1.266330e+08,1.262610e+08,1.256816e+08,NaN
18,Latvia,LVA,"Population, total",SP.POP.TOTL,2120979.0,2152681.0,2181586.0,2210919.0,2240623.0,2265919.0,...,2.012647e+06,1.993782e+06,1.977527e+06,1.959537e+06,1.942248e+06,1.927174e+06,1.913822e+06,1.900449e+06,1.884490e+06,NaN
19,Lithuania,LTU,"Population, total",SP.POP.TOTL,2778550.0,2823550.0,2863350.0,2898950.0,2935200.0,2971450.0,...,2.957689e+06,2.932367e+06,2.904910e+06,2.868231e+06,2.828403e+06,2.801543e+06,2.794137e+06,2.794885e+06,2.800839e+06,NaN
20,Luxembourg,LUX,"Population, total",SP.POP.TOTL,313970.0,316845.0,320750.0,324100.0,327750.0,331500.0,...,5.433600e+05,5.563190e+05,5.696040e+05,5.820140e+05,5.963360e+05,6.079500e+05,6.200010e+05,6.304190e+05,6.400640e+05,NaN
21,Mexico,MEX,"Population, total",SP.POP.TOTL,36268055.0,37439317.0,38683283.0,39982118.0,41333878.0,42737991.0,...,1.172907e+08,1.187559e+08,1.201499e+08,1.215192e+08,1.228393e+08,1.240139e+08,1.250853e+08,1.259983e+08,1.267051e+08,NaN
22,Netherlands,NLD,"Population, total",SP.POP.TOTL,11486631.0,11638712.0,11805689.0,11965966.0,12127120.0,12294732.0,...,1.680443e+07,1.686501e+07,1.693992e+07,1.703031e+07,1.713130e+07,1.723162e+07,1.734487e+07,1.744150e+07,1.753304e+07,NaN
23,New Zealand,NZL,"Population, total",SP.POP.TOTL,2371800.0,2419700.0,2482000.0,2531800.0,2585400.0,2628400.0,...,4.442100e+06,4.516500e+06,4.609400e+06,4.714100e+06,4.813600e+06,4.900600e+06,4.979200e+06,5.090200e+06,5.122600e+06,NaN
24,Norway,NOR,"Population, total",SP.POP.TOTL,3581239.0,3609800.0,3638918.0,3666537.0,3694339.0,3723168.0,...,5.079623e+06,5.137232e+06,5.188607e+06,5.234519e+06,5.276968e+06,5.311916e+06,5.347896e+06,5.379475e+06,5.408320e+06,NaN
25,Poland,POL,"Population, total",SP.POP.TOTL,29637450.0,29964000.0,30308500.0,30712000.0,31139450.0,31444950.0,...,3.804020e+07,3.801174e+07,3.798641e+07,3.797009e+07,3.797483e+07,3.797475e+07,3.796548e+07,3.789907e+07,3.774712e+07,NaN
26,Portugal,PRT,"Population, total",SP.POP.TOTL,8857716.0,8929316.0,8993985.0,9030355.0,9035365.0,8998595.0,...,1.045730e+07,1.040106e+07,1.035808e+07,1.032545e+07,1.030030e+07,1.028382e+07,1.028626e+07,1.029708e+07,1.032515e+07,NaN
27,Slovak Republic,SVK,"Population, total",SP.POP.TOTL,4068095.0,4191667.0,4238188.0,4282017.0,4327341.0,4370983.0,...,5.413393e+06,5.418649e+06,5.423801e+06,5.430798e+06,5.439232e+06,5.446771e+06,5.454147e+06,5.458827e+06,5.447247e+06,NaN
28,Slovenia,SVN,"Population, total",SP.POP.TOTL,1584720.0,1594131.0,1603649.0,1616971.0,1632114.0,1649160.0,...,2.059953e+06,2.061980e+06,2.063531e+06,2.065042e+06,2.066388e+06,2.073894e+06,2.088385e+06,2.102419e+06,2.108079e+06,NaN
29,Spain,ESP,"Population, total",SP.POP.TOTL,30455000.0,30739250.0,31023366.0,31296651.0,31609195.0,31954292.0,...,4.662004e+07,4.648088e+07,4.644483e+07,4.648406e+07,4.659324e+07,4.679775e+07,4.713484e+07,4.736566e+07,4.741575e+07,NaN
30,Sweden,SWE,"Population, total",SP.POP.TOTL,7484656.0,7519998.0,7561588.0,7604328.0,7661354.0,7733853.0,...,9.600379e+06,9.696110e+06,9.799186e+06,9.923085e+06,1.005770e+07,1.017521e+07,1.027889e+07,1.035344e+07,1.041581e+07,NaN
31,Switzerland,CHE,"Population, total",SP.POP.TOTL,5327827.0,5434294.0,5573815.0,5694247.0,5789228.0,5856472.0,...,8.089346e+06,8.188649e+06,8.282396e+06,8.373338e+06,8.451840e+06,8.514329e+06,8.575280e+06,8.638167e+06,8.703405e+06,NaN
32,United Kingdom,GBR,"Population, total",SP.POP.TOTL,52400000.0,52800000.0,53250000.0,53650000.0,54000000.0,54348050.0,...,6.412827e+07,6.460230e+07,6.511622e+07,6.561159e+07,6.605886e+07,6.646034e+07,6.683633e+07,6.708100e+07,6.732657e+07,NaN
33,United States,USA,"Population, total",SP.POP.TOTL,180671000.0,183691000.0,186538000.0,189242000.0,191889000.0,194303000.0,...,3.160599e+08,3.183863e+08,3.207390e+08,3.230718e+08,3.251221e+08,3.268382e+08,3.283300e+08,3.315011e+08,3.318937e+08,NaN
34,Argentina,ARG,"Population, total",SP.POP.TOTL,20349744.0,20680653.0,21020359.0,21364017.0,21708487.0,22053661.0,...,4.220294e+07,4.266950e+07,4.313197e+07,4.359037e+07,4.404481e+07,4.449450e+07,4.493871e+07,4.537676e+07,4.580875e+07,NaN
35,Brazil,BRA,"Population, total",SP.POP.TOTL,73092515.0,75330008.0,77599218.0,79915555.0,82262794.0,84623747.0,...,2.017218e+08,2.034596e+08,2.051882e+08,2.068596e+08,2.085050e+08,2.101666e+08,2.117829e+08,2.131963e+08,2.143262e+08,NaN
36,Bulgaria,BGR,"Population, total",SP.POP.TOTL,7867374.0,7943118.0,8012946.0,8078145.0,8144340.0,8204168.0,...,7.265115e+06,7.223938e+06,7.177991e+06,7.127822e+06,7.075947e+06,7.025037e+06,6.975761e+06,6.934015e+06,6.877743e+06,NaN
37,Croatia,HRV,"Population, total",SP.POP.TOTL,4140181.0,4167292.0,4196712.0,4225675.0,4252876.0,4280923.0,...,4.255689e+06,4.238389e+06,4.203604e+06,4.174349e+06,4.124531e+06,4.087843e+06,4.065253e+06,4.047680e+06,3.899000e+06,NaN
38,Cyprus,CYP,"Population, total",SP.POP.TOTL,585725.0,594771.0,601095.0,607072.0,612338.0,617345.0,...,1.166968e+06,1.176995e+06,1.187280e+06,1.197881e+06,1.208523e+06,1.218831e+06,1.228836e+06,1.237537e+06,1.244188e+06,NaN
39,India,IND,"Population, total",SP.POP.TOTL,445954579.0,456351876.0,467024193.0,477933619.0,489059309.0,500114346.0,...,1.291132e+09,1.307247e+09,1.322867e+09,1.338636e+09,1.354196e+09,1.369003e+09,1.383112e+09,1.396387e+09,1.407564e+09,NaN
40,Malta,MLT,"Population, total",SP.POP.TOTL,326550.0,325250.0,323900.0,322550.0,321250.0,318800.0,...,4.259670e+05,4.345580e+05,4.450530e+05,4.553560e+05,4.679990e+05,4.846300e+05,5.040620e+05,5.153320e+05,5.185360e+05,NaN
41,North Macedonia,MKD,"Population, total",SP.POP.TOTL,1462368.0,1481112.0,1497338.0,1511854.0,1529507.0,1547982.0,...,2.064032e+06,2.067471e+06,2.070226e+06,2.072490e+06,2.074502e+06,2.076217e+06,2.076694e+06,2.072531e+06,2.065092e+06,NaN
42,Romania,ROU,"Population, total",SP.POP.TOTL,18406905.0,18555250.0,18676550.0,18797850.0,18919126.0,19031576.0,...,1.998369e+07,1.990898e+07,1.981562e+07,1.970227e+07,1.958872e+07,1.947397e+07,1.937165e+07,1.926525e+07,1.911988e+07,NaN
43,Serbia,SRB,"Population, total",SP.POP.TOTL,6608000.0,6655000.0,6696000.0,6732000.0,6765000.0,6794000.0,...,7.164132e+06,7.130576e+06,7.095383e+06,7.058322e+06,7.020858e+06,6.982604e+06,6.945235e+06,6.899126e+06,6.834326e+06,NaN

In [8]:
main_df = pd.merge(main_df,gdp_df,how='inner',on='Country Name')
main_df

,Country Name,Country Code_x,Indicator Name_x,Indicator Code_x,1960_x,1961_x,1962_x,1963_x,1964_x,1965_x,...,2012_y,2013_y,2014_y,2015_y,2016_y,2017_y,2018_y,2019_y,2020_y,2021_y
0,Australia,AUS,"Population, total",SP.POP.TOTL,10276477.0,10483000.0,10742000.0,10950000.0,11167000.0,11388000.0,...,1.546890e+12,1.576380e+12,1.467550e+12,1.350620e+12,1.206540e+12,1.326520e+12,1.428290e+12,1.392230e+12,1.326900e+12,1.552670e+12
1,Austria,AUT,"Population, total",SP.POP.TOTL,7047539.0,7086299.0,7129864.0,7175811.0,7223801.0,7270889.0,...,4.094020e+11,4.301910e+11,4.425850e+11,3.819710e+11,3.958370e+11,4.172610e+11,4.549910e+11,4.446210e+11,4.352250e+11,4.803680e+11
2,Belgium,BEL,"Population, total",SP.POP.TOTL,9153489.0,9183948.0,9220578.0,9289770.0,9378113.0,9463667.0,...,4.961530e+11,5.217910e+11,5.353900e+11,4.623360e+11,4.760630e+11,5.027650e+11,5.432990e+11,5.358310e+11,5.252120e+11,5.941040e+11
3,Canada,CAN,"Population, total",SP.POP.TOTL,17909356.0,18271000.0,18614000.0,18964000.0,19325000.0,19678000.0,...,1.828370e+12,1.846600e+12,1.805750e+12,1.556510e+12,1.527990e+12,1.649270e+12,1.725330e+12,1.742020e+12,1.645420e+12,1.988340e+12
4,Chile,CHL,"Population, total",SP.POP.TOTL,8141820.0,8313535.0,8486120.0,8656006.0,8825046.0,8994936.0,...,2.671760e+11,2.772390e+11,2.594050e+11,2.424970e+11,2.492990e+11,2.763650e+11,2.954030e+11,2.785850e+11,2.527270e+11,3.170590e+11
5,Colombia,COL,"Population, total",SP.POP.TOTL,15687688.0,16182414.0,16691282.0,17210956.0,17739754.0,18275814.0,...,3.709210e+11,3.821160e+11,3.811120e+11,2.934820e+11,2.828250e+11,3.118840e+11,3.341980e+11,3.231100e+11,2.703000e+11,3.144640e+11
6,Costa Rica,CRI,"Population, total",SP.POP.TOTL,1346302.0,1396138.0,1447037.0,1498647.0,1550661.0,1602736.0,...,4.723165e+10,5.094967e+10,5.201641e+10,5.644192e+10,5.884702e+10,6.051604e+10,6.242017e+10,6.441767e+10,6.215800e+10,6.428244e+10
7,Denmark,DNK,"Population, total",SP.POP.TOTL,4579603.0,4611687.0,4647727.0,4684483.0,4722072.0,4759012.0,...,3.271490e+11,3.435840e+11,3.529940e+11,3.026730e+11,3.131160e+11,3.321210e+11,3.568410e+11,3.464990e+11,3.552220e+11,3.983030e+11
8,Estonia,EST,"Population, total",SP.POP.TOTL,1211537.0,1225077.0,1241623.0,1258857.0,1277086.0,1294566.0,...,2.301915e+10,2.511575e+10,2.663408e+10,2.289076e+10,2.407283e+10,2.692439e+10,3.062472e+10,3.108190e+10,3.137040e+10,3.719117e+10
9,Finland,FIN,"Population, total",SP.POP.TOTL,4429634.0,4461005.0,4491443.0,4523309.0,4548543.0,4563732.0,...,2.582900e+11,2.713620e+11,2.748630e+11,2.345340e+11,2.407710e+11,2.556480e+11,2.757080e+11,2.685150e+11,2.718920e+11,2.973020e+11
10,France,FRA,"Population, total",SP.POP.TOTL,46649927.0,47161641.0,47679792.0,48189939.0,48733997.0,49282756.0,...,2.683670e+12,2.811880e+12,2.855960e+12,2.439190e+12,2.472960e+12,2.595150e+12,2.790960e+12,2.728870e+12,2.639010e+12,2.957880e+12
11,Germany,DEU,"Population, total",SP.POP.TOTL,72814900.0,73377632.0,74025784.0,74714353.0,75318337.0,75963695.0,...,3.527140e+12,3.733800e+12,3.889090e+12,3.357590e+12,3.469850e+12,3.690850e+12,3.974440e+12,3.888230e+12,3.889670e+12,4.259930e+12
12,Greece,GRC,"Population, total",SP.POP.TOTL,8331725.0,8398050.0,8448233.0,8479625.0,8510429.0,8550333.0,...,2.420290e+11,2.389080e+11,2.354580e+11,1.956840e+11,1.931480e+11,1.998440e+11,2.120490e+11,2.052570e+11,1.889260e+11,2.148740e+11
13,Hungary,HUN,"Population, total",SP.POP.TOTL,9983967.0,10029321.0,10061734.0,10087947.0,10119835.0,10147935.0,...,1.288140e+11,1.356840e+11,1.410340e+11,1.251740e+11,1.286100e+11,1.431120e+11,1.605650e+11,1.639890e+11,1.571820e+11,1.818480e+11
14,Iceland,ISL,"Population, total",SP.POP.TOTL,175574.0,179029.0,182378.0,185653.0,188983.0,192286.0,...,1.475151e+10,1.612506e+10,1.786766e+10,1.751721e+10,2.079317e+10,2.472829e+10,2.626413e+10,2.482610e+10,2.169467e+10,2.560242e+10
15,Ireland,IRL,"Population, total",SP.POP.TOTL,2828600.0,2824400.0,2836050.0,2852650.0,2866550.0,2877300.0,...,2.256290e+11,2.383410e+11,2.591710e+11,2.917750e+11,2.990910e+11,3.363780e+11,3.857370e+11,3.993220e+11,4.258520e+11,5.041830e+11
16,Italy,ITA,"Population, total",SP.POP.TOTL,50199700.0,50536350.0,50879450.0,51252000.0,51675350.0,52112350.0,...,2.086960e+12,2.141920e+12,2.162010e+12,1.836640e+12,1.877070e+12,1.961800e+12,2.091930e+12,2.011300e+12,1.896760e+12,2.107700e+12
17,Japan,JPN,"Population, total",SP.POP.TOTL,93216000.0,94055000.0,94933000.0,95900000.0,96903000.0,97952000.0,...,6.272360e+12,5.212330e+12,4.896990e+12,4.444930e+12,5.003680e+12,4.930840e+12,5.037840e+12,5.123320e+12,5.040110e+12,4.940880e+12
18,Latvia,LVA,"Population, total",SP.POP.TOTL,2120979.0,2152681.0,2181586.0,2210919.0,2240623.0,2265919.0,...,2.816990e+10,3.020478e+10,3.138690e+10,2.726309e+10,2.808360e+10,3.048381e+10,3.442902e+10,3.434396e+10,3.460174e+10,3.985350e+10
19,Lithuania,LTU,"Population, total",SP.POP.TOTL,2778550.0,2823550.0,2863350.0,2898950.0,2935200.0,2971450.0,...,4.292745e+10,4.652342e+10,4.853366e+10,4.143553e+10,4.304731e+10,4.775874e+10,5.375141e+10,5.475151e+10,5.684662e+10,6.644526e+10
20,Luxembourg,LUX,"Population, total",SP.POP.TOTL,313970.0,316845.0,320750.0,324100.0,327750.0,331500.0,...,5.977638e+10,6.520328e+10,6.880481e+10,6.007158e+10,6.221689e+10,6.571218e+10,7.100036e+10,6.982564e+10,7.399259e+10,8.550624e+10
21,Mexico,MEX,"Population, total",SP.POP.TOTL,36268055.0,37439317.0,38683283.0,39982118.0,41333878.0,42737991.0,...,1.201090e+12,1.274440e+12,1.315350e+12,1.171870e+12,1.078490e+12,1.158910e+12,1.222410e+12,1.269010e+12,1.090520e+12,1.272840e+12
22,Netherlands,NLD,"Population, total",SP.POP.TOTL,11486631.0,11638712.0,11805689.0,11965966.0,12127120.0,12294732.0,...,8.389230e+11,8.771730e+11,8.921680e+11,7.655730e+11,7.840600e+11,8.338700e+11,9.140430e+11,9.101940e+11,9.097930e+11,1.012850e+12
23,New Zealand,NZL,"Population, total",SP.POP.TOTL,2371800.0,2419700.0,2482000.0,2531800.0,2585400.0,2628400.0,...,1.762070e+11,1.909070e+11,2.013130e+11,1.780640e+11,1.888380e+11,2.066240e+11,2.119530e+11,2.134350e+11,2.117350e+11,2.498860e+11
24,Norway,NOR,"Population, total",SP.POP.TOTL,3581239.0,3609800.0,3638918.0,3666537.0,3694339.0,3723168.0,...,5.095060e+11,5.227620e+11,4.984100e+11,3.858020e+11,3.688270e+11,3.983940e+11,4.370000e+11,4.049410e+11,3.621980e+11,4.821750e+11
25,Poland,POL,"Population, total",SP.POP.TOTL,29637450.0,29964000.0,30308500.0,30712000.0,31139450.0,31444950.0,...,4.952370e+11,5.157650e+11,5.390880e+11,4.771110e+11,4.700230e+11,5.246460e+11,5.887830e+11,5.960550e+11,5.994490e+11,6.794450e+11
26,Portugal,PRT,"Population, total",SP.POP.TOTL,8857716.0,8929316.0,8993985.0,9030355.0,9035365.0,8998595.0,...,2.162240e+11,2.264340e+11,2.299020e+11,1.993940e+11,2.064260e+11,2.213580e+11,2.423130e+11,2.399870e+11,2.290320e+11,2.536630e+11
27,Slovak Republic,SVK,"Population, total",SP.POP.TOTL,4068095.0,4191667.0,4238188.0,4282017.0,4327341.0,4370983.0,...,9.462373e+10,9.893522e+10,1.014370e+11,8.890088e+10,8.995270e+10,9.564997e+10,1.061380e+11,1.057200e+11,1.066970e+11,1.165270e+11
28,Slovenia,SVN,"Population, total",SP.POP.TOTL,1584720.0,1594131.0,1603649.0,1616971.0,1632114.0,1649160.0,...,4.657779e+10,4.841566e+10,4.999719e+10,4.310751e+10,4.476672e+10,4.858910e+10,5.417788e+10,5.433159e+10,5.370680e+10,6.174859e+10
29,Spain,ESP,"Population, total",SP.POP.TOTL,30455000.0,30739250.0,31023366.0,31296651.0,31609195.0,31954292.0,...,1.324750e+12,1.355580e+12,1.371820e+12,1.196160e+12,1.233550e+12,1.313250e+12,1.421700e+12,1.394320e+12,1.276960e+12,1.427380e+12
30,Sweden,SWE,"Population, total",SP.POP.TOTL,7484656.0,7519998.0,7561588.0,7604328.0,7661354.0,7733853.0,...,5.524840e+11,5.868420e+11,5.819640e+11,5.051040e+11,5.156550e+11,5.410190e+11,5.554550e+11,5.338800e+11,5.470540e+11,6.356640e+11
31,Switzerland,CHE,"Population, total",SP.POP.TOTL,5327827.0,5434294.0,5573815.0,5694247.0,5789228.0,5856472.0,...,6.864200e+11,7.062350e+11,7.265380e+11,6.941180e+11,6.878950e+11,6.952010e+11,7.255690e+11,7.213690e+11,7.399140e+11,8.006400e+11
32,United Kingdom,GBR,"Population, total",SP.POP.TOTL,52400000.0,52800000.0,53250000.0,53650000.0,54000000.0,54348050.0,...,2.706340e+12,2.786320e+12,3.065220e+12,2.934860e+12,2.699660e+12,2.683400e+12,2.878150e+12,2.857060e+12,2.704610e+12,3.131380e+12
33,United States,USA,"Population, total",SP.POP.TOTL,180671000.0,183691000.0,186538000.0,189242000.0,191889000.0,194303000.0,...,1.625400e+13,1.684320e+13,1.755070e+13,1.820600e+13,1.869510e+13,1.947730e+13,2.053310e+13,2.138100e+13,2.106050e+13,2.331510e+13
34,Argentina,ARG,"Population, total",SP.POP.TOTL,20349744.0,20680653.0,21020359.0,21364017.0,21708487.0,22053661.0,...,5.459820e+11,5.520250e+11,5.263200e+11,5.947490e+11,5.575310e+11,6.436290e+11,5.248200e+11,4.477550e+11,3.855400e+11,4.872270e+11
35,Brazil,BRA,"Population, total",SP.POP.TOTL,73092515.0,75330008.0,77599218.0,79915555.0,82262794.0,84623747.0,...,2.465190e+12,2.472810e+12,2.455990e+12,1.802210e+12,1.795700e+12,2.063510e+12,1.916950e+12,1.873270e+12,1.448560e+12,1.608980e+12
36,Bulgaria,BGR,"Population, total",SP.POP.TOTL,7867374.0,7943118.0,8012946.0,8078145.0,8144340.0,8204168.0,...,5.430086e+10,5.581014e+10,5.708201e+10,5.078200e+10,5.395390e+10,5.919945e+10,6.636354e+10,6.891588e+10,7.024028e+10,8.405631e+10
37,Croatia,HRV,"Population, total",SP.POP.TOTL,4140181.0,4167292.0,4196712.0,4225675.0,4252876.0,4280923.0,...,5.736936e+10,5.903207e+10,5.842398e+10,5.024278e+10,5.239749e+10,5.632384e+10,6.231684e+10,6.232798e+10,5.747201e+10,6.895508e+10
38,Cyprus,CYP,"Population, total",SP.POP.TOTL,585725.0,594771.0,601095.0,607072.0,612338.0,617345.0,...,2.504866e+10,2.396114e+10,2.322678e+10,1.990919e+10,2.104695e+10,2.294673e+10,2.559647e+10,2.594450e+10,2.500845e+10,2.840787e+10
39,India,IND,"Population, total",SP.POP.TOTL,445954579.0,456351876.0,467024193.0,477933619.0,489059309.0,500114346.0,...,1.827640e+12,1.856720e+12,2.039130e+12,2.103590e+12,2.294800e+12,2.651470e+12,2.702930e+12,2.831550e+12,2.667690e+12,3.176300e+12
40,Malta,MLT,"Population, total",SP.POP.TOTL,326550.0,325250.0,323900.0,322550.0,321250.0,318800.0,...,9.462290e+09,1.055160e+10,1.162628e+10,1.109142e+10,1.166825e+10,1.348938e+10,1.529877e+10,1.572585e+10,1.493307e+10,1.736404e+10
41,North Macedonia,MKD,"Population, total",SP.POP.TOTL,1462368.0,1481112.0,1497338.0,1511854.0,1529507.0,1547982.0,...,9.745251e+09,1.081771e+10,1.136227e+10,1.006452e+10,1.067247e+10,1.130706e+10,1.268307e+10,1.260634e+10,1.236358e+10,1.382505e+10
42,Romania,ROU,"Population, total",SP.POP.TOTL,18406905.0,18555250.0,18676550.0,18797850.0,18919126.0,19031576.0,...,1.791330e+11,1.897900e+11,1.997120e+11,1.778820e+11,1.852870e+11,2.101470e+11,2.433170e+11,2.510190e+11,2.513620e+11,2.840880e+11
43,Serbia,SRB,"Population, total",SP.POP.TOTL,6608000.0,6655000.0,6696000.0,6732000.0,6765000.0,6794000.0,...,4.330925e+10,4.839424e+10,4.706221e+10,3.965596e+10,4.069264e+10,4.417906e+10,5.064065e+10,5.151422e+10,5.335648e+10,6.308205e+10

In [9]:
main_df.columns

Index(['Country Name', 'Country Code_x', 'Indicator Name_x',
       'Indicator Code_x', '1960_x', '1961_x', '1962_x', '1963_x', '1964_x',
       '1965_x',
       ...
       '2012_y', '2013_y', '2014_y', '2015_y', '2016_y', '2017_y', '2018_y',
       '2019_y', '2020_y', '2021_y'],
      dtype='object', length=132)

In [19]:
main_df_copy = main_df.melt(id_vars=['Country Name', 'Country Code_x', 'Indicator Name_x',
       'Indicator Code_x'], 
        var_name="Date", 
        value_name="Value")

main_df_copy['Date'] = main_df_copy['Date'].str.replace('_x', '')
main_df_copy['Date'] = main_df_copy['Date'].str.replace('_y', '')

In [25]:
main_df_copy['Country Name'].nunique()

44

In [13]:
main_df_copy

,Country Name,Country Code_x,Indicator Name_x,Indicator Code_x,Date,Value
0,Australia,AUS,"Population, total",SP.POP.TOTL,1960,1.02765e+07
1,Austria,AUT,"Population, total",SP.POP.TOTL,1960,7.04754e+06
2,Belgium,BEL,"Population, total",SP.POP.TOTL,1960,9.15349e+06
3,Canada,CAN,"Population, total",SP.POP.TOTL,1960,1.79094e+07
4,Chile,CHL,"Population, total",SP.POP.TOTL,1960,8.14182e+06
...,...,...,...,...,...,...
5627,India,IND,"Population, total",SP.POP.TOTL,2021_y,3.1763e+12
5628,Malta,MLT,"Population, total",SP.POP.TOTL,2021_y,1.7364e+10
5629,North Macedonia,MKD,"Population, total",SP.POP.TOTL,2021_y,1.3825e+10
5630,Romania,ROU,"Population, total",SP.POP.TOTL,2021_y,2.84088e+11
5631,Serbia,SRB,"Population, total",SP.POP.TOTL,2021_y,6.3082e+10

In [20]:
# Save updated dataframe to csv
main_df_copy.to_csv("Resources/popn_gdp_v1.csv", index=False)